services:
  # bot:
  #   build: ./bot
  #   container_name: bot
  #   environment:
  #     - TZ=Asia/Vladivostok
  #   volumes:
  #   - bot_settings:/app/settings
  #   restart: always
  #   env_file:
  #     - .env

  # asana:
  #   build:
  #     dockerfile: ./asana/Dockerfile
  #     context: .
  #   restart: always
  #   container_name: asana

  # nats:
  #   image: nats@sha256:031f9a7ed1e08524b3dff604bfaee5177baa95c25f039822b8d224a42373be4e
  #   container_name: nats
  #   ports:
  #     - "4222:4222"  # основной порт клиента
  #     - "8222:8222"  # веб-интерфейс/мониторинг
  #   command: >
  #     -js
  #     -m 8222
  #     -sd /data
  #   restart: always
  #   volumes: 
  #     - nats_jetstream:/data

  main:
    container_name: main
    build: ./src
    ports:
      - "8000:8000"
    volumes:
      - database:/app/db
      - ./src:/app
    environment:
      - TZ=Asia/Vladivostok
    restart: always
    env_file:
      - .env
    command: --reload

  ssh-tunnel:
    build: ./ssh_tunnel
    container_name: ssh_tunnel
    restart: always
    stop_grace_period: 2s
    command:
      # localhost.run: randomly changing url
      # ssh -o StrictHostKeyChecking=no -R 80:api:8000 nokey@localhost.run

      # serveo.net: not always available
      # ssh -o StrictHostKeyChecking=no -R testyandexformstgbot:80:api:8000 serveo.net

      # (recomended) PageKite
      --defaults --service_on=http:yandexformstestbot.pagekite.me:main:8000:cc6f9ka33aza36cka342x873z7z3ced2 --logfile=./logs.txt

volumes:
  database:
  bot_settings:
  # nats_jetstream: