services:
  bot:
    build: ./bot
    environment:
      - TZ=Asia/Vladivostok
    volumes:
    - bot_settings:/app/settings
    restart: always
    env_file:
      - .env

  api:
    container_name: fastapi
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - bot_api_db:/app/db
    restart: always

  ssh-tunnel:
    build: ./ssh_tunnel
    container_name: ssh_tunnel
    restart: always
    command:
      # localhost.run: randomly changing url
      # ssh -o StrictHostKeyChecking=no -R 80:api:8000 nokey@localhost.run

      # serveo.net: not always available
      # ssh -o StrictHostKeyChecking=no -R testyandexformstgbot:80:api:8000 serveo.net

      # (recomended) PageKite
      --defaults --service_on=http:yandexformstestbot.pagekite.me:api:8000:cc6f9ka33aza36cka342x873z7z3ced2

volumes:
  bot_api_db:
  bot_settings: